# Generated by Django 4.0.8 on 2022-10-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_name_user_respect_user_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clan'),
        ),
    ]
